
Press ENTER or type command to continue
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-9.0.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pyaudio is already the newest version (0.2.8-1build2).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-image-4.10.0-28-generic
  linux-image-extra-4.10.0-28-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libjack-jackd2-dev is already the newest version (1.9.10+20150825git1ed50c92~dfsg-1ubuntu1).
portaudio19-dev is already the newest version (19+svn20140130-1build1).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-image-4.10.0-28-generic
  linux-image-extra-4.10.0-28-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: bs4 in /home/philip/.local/lib/python3.6/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: send2trash in /home/philip/.local/lib/python3.6/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: httplib2 in /home/philip/.local/lib/python3.6/site-packages (from -r requirements.txt (line 3))
Collecting pyaudio (from -r requirements.txt (line 4))
  Using cached PyAudio-0.2.11.tar.gz
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5))
Collecting decorator (from -r requirements.txt (line 6))
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Collecting markdown (from -r requirements.txt (line 7))
Requirement already satisfied: beautifulsoup4 in /home/philip/.local/lib/python3.6/site-packages (from bs4->-r requirements.txt (line 1))
Building wheels for collected packages: pyaudio
  Running setup.py bdist_wheel for pyaudio ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d1fb37gy/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpb818g25bpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  copying src/pyaudio.py -> build/lib.linux-x86_64-3.6
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
  src/_portaudiomodule.c:28:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio, decorator, markdown
  Running setup.py install for pyaudio ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d1fb37gy/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-01jrueyv-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.6
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
    src/_portaudiomodule.c:28:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-d1fb37gy/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-01jrueyv-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-d1fb37gy/pyaudio/
Traceback (most recent call last):
  File "./runanki3.6", line 3, in <module>
    import aqt
  File "/home/philip/code/anki/aqt/__init__.py", line 4, in <module>
    from anki import version as _version
  File "/home/philip/code/anki/anki/__init__.py", line 14, in <module>
    from anki.storage import Collection
  File "/home/philip/code/anki/anki/storage.py", line 11, in <module>
    from anki.collection import _Collection
  File "/home/philip/code/anki/anki/collection.py", line 18, in <module>
    from anki.hooks import  runFilter, runHook
  File "/home/philip/code/anki/anki/hooks.py", line 16, in <module>
    import decorator
ModuleNotFoundError: No module named 'decorator'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "./runanki3.6", line 3, in <module>
    import aqt
  File "/home/philip/code/anki/aqt/__init__.py", line 4, in <module>
    from anki import version as _version
  File "/home/philip/code/anki/anki/__init__.py", line 14, in <module>
    from anki.storage import Collection
  File "/home/philip/code/anki/anki/storage.py", line 11, in <module>
    from anki.collection import _Collection
  File "/home/philip/code/anki/anki/collection.py", line 18, in <module>
    from anki.hooks import  runFilter, runHook
  File "/home/philip/code/anki/anki/hooks.py", line 16, in <module>
    import decorator
ModuleNotFoundError: No module named 'decorator'

shell returned 1

